trigger:
- none

pr:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

steps:
- script: docker build . --file devcontainer.Dockerfile --tag experiments:$(date +%s)
  displayName: 'Build the dev container'

